"""Run with Blender --background --factory-startup --python-exit-code 1."""
import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import bpy
from gamify import generation_defaults

bpy.ops.preferences.addon_enable(module='rigify')
for module in list(sys.modules.values()):
    if (module is not None and module is not generation_defaults
            and getattr(module, '__name__', '').endswith('.generation_defaults')
            and getattr(module, '_enabled', False)):
        module.unregister()
generation_defaults.register()
bpy.ops.object.armature_add()
meta = bpy.context.object
meta.pose.bones[0].rigify_type = 'basic.super_copy'
collection = meta.data.collections.new('Controls')
collection.rigify_ui_row = 1
collection.assign(meta.data.bones[0])
assert 'FINISHED' in bpy.ops.pose.rigify_generate()
rig = meta.data.rigify_target_rig
rig.pose.bones['Bone'].location.x = 0.3
rig.pose.bones['Bone'].keyframe_insert(data_path='location', frame=1)
rig.pose.bones['Bone'].location.x = 0.8
rig.pose.bones['Bone'].keyframe_insert(data_path='location', frame=20)
animation = rig.animation_data
action = animation.action
slot = animation.action_slot
animation.action = None
track = animation.nla_tracks.new()
track.name = 'Walk Track'
strip = track.strips.new('Walk Clip', 10, action)
strip.action_slot = slot
strip.scale = 1.5
strip.repeat = 2
strip.blend_type = 'ADD'
strip.extrapolation = 'NOTHING'
strip.use_auto_blend = False
strip.blend_in = 2
strip.blend_out = 3
strip.use_animated_influence = True
strip.influence = 0.4
strip.keyframe_insert(data_path='influence', frame=10)
strip.influence = 0.8
strip.keyframe_insert(data_path='influence', frame=20)
strip.fcurves[0].modifiers.new('NOISE').strength = 0.2
track.mute = True
second = animation.nla_tracks.new(prev=track)
second.name = 'Second Track'
second.strips.new('Second Clip', 80, action).action_slot = slot
animation.action = action
animation.action_slot = slot
animation.action_influence = 0.7
expected = (strip.frame_start, strip.frame_end, strip.scale, strip.repeat)
# A driver generated by Rigify must survive; obsolete old drivers must not.
obsolete = rig.driver_add('hide_render')
obsolete.driver.expression = '0'

for flip in (False, True, True):
    bpy.ops.object.mode_set(mode='OBJECT')
    bpy.ops.object.select_all(action='DESELECT')
    meta.select_set(True)
    bpy.context.view_layer.objects.active = meta
    bpy.context.scene.gamify_root_flip_y = flip
    assert 'FINISHED' in bpy.ops.pose.rigify_generate()
    rig = meta.data.rigify_target_rig
    animation = rig.animation_data
    assert animation.action == action
    assert animation.action_slot == slot
    assert abs(animation.action_influence - 0.7) < 1e-6
    assert [t.name for t in animation.nla_tracks] == ['Walk Track', 'Second Track']
    track = animation.nla_tracks[0]
    strip = track.strips[0]
    assert track.mute
    assert strip.action == action and strip.action_slot == slot
    assert (strip.frame_start, strip.frame_end, strip.scale, strip.repeat) == expected
    assert strip.blend_type == 'ADD' and strip.extrapolation == 'NOTHING'
    assert strip.blend_in == 2 and strip.blend_out == 3
    assert strip.use_animated_influence
    assert len(strip.fcurves[0].keyframe_points) == 2
    assert strip.fcurves[0].modifiers[0].type == 'NOISE'
    assert abs(strip.fcurves[0].modifiers[0].strength - 0.2) < 1e-6
    assert all(d.data_path != 'hide_render' for d in animation.drivers)
    assert not any(o.name.startswith(('Gamify animation backup', 'Gamify generated drivers'))
                   for o in bpy.data.objects)

# Verify regenerated drivers retain real target IDs when restored.
from gamify.nla_preservation import snapshot_animation, restore_animation
backup = snapshot_animation(rig)
driver = rig.driver_add('hide_render')
driver.driver.type = 'SCRIPTED'
var = driver.driver.variables.new()
var.type = 'SINGLE_PROP'
var.targets[0].id = rig
var.targets[0].data_path = 'location.x'
restore_animation(bpy.context, rig, backup)
bpy.data.objects.remove(backup, do_unlink=True)
assert rig.animation_data.drivers[-1].driver.variables[0].targets[0].id == rig
# A failed generation must also restore the saved animation and clean backups.
original_generate = generation_defaults._original_generate
def fail_generation(context, metarig):
    metarig.data.rigify_target_rig.animation_data_clear()
    raise RuntimeError('Expected generation failure')
generation_defaults._original_generate = fail_generation
bpy.context.scene.gamify_root_flip_y = False
try:
    from rigify import generate
    generate.generate_rig(bpy.context, meta)
except RuntimeError as error:
    assert str(error) == 'Expected generation failure'
else:
    raise AssertionError('Expected generation failure')
finally:
    generation_defaults._original_generate = original_generate
assert rig.animation_data.action == action
assert [t.name for t in rig.animation_data.nla_tracks] == ['Walk Track', 'Second Track']
assert not any(o.name.startswith(('Gamify animation backup', 'Gamify generated drivers'))
               for o in bpy.data.objects)
generation_defaults.unregister()
print('NLA_PRESERVATION_OK')
