import bpy

from rna_prop_ui import rna_idprop_ui_create

from mathutils import Color
from mathutils import Euler
from mathutils import Vector

bl_description = "Create the Gamify plush character metarig."

def create(obj):  # noqa
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    bone_collections = {}

    for bcoll in list(arm.collections_all):
        arm.collections.remove(bcoll)

    def add_bone_collection(name, *, parent=None, ui_row=0, ui_title='', sel_set=False, color_set_id=0):
        new_bcoll = arm.collections.new(name, parent=bone_collections.get(parent))
        new_bcoll.rigify_ui_row = ui_row
        new_bcoll.rigify_ui_title = ui_title
        new_bcoll.rigify_sel_set = sel_set
        new_bcoll.rigify_color_set_id = color_set_id
        bone_collections[name] = new_bcoll

    def assign_bone_collections(pose_bone, *coll_names):
        assert not len(pose_bone.bone.collections)
        for name in coll_names:
            bone_collections[name].assign(pose_bone)

    def assign_bone_collection_refs(params, attr_name, *coll_names):
        ref_list = getattr(params, attr_name + '_coll_refs', None)
        if ref_list is not None:
            for name in coll_names:
                ref_list.add().set_collection(bone_collections[name])

    add_bone_collection('Root', ui_row=19)
    add_bone_collection('Face', ui_row=1)
    add_bone_collection('Mouth', parent='Face', ui_row=2)
    add_bone_collection('Tongue', parent='Face', ui_row=2)
    add_bone_collection('Eyes', parent='Face', ui_row=2)
    add_bone_collection('Torso', ui_row=4)
    add_bone_collection('Torso (Tweak)', ui_row=5)
    add_bone_collection('Fingers', ui_row=7)
    add_bone_collection('Fingers (Detail)', ui_row=8, ui_title='(Detail)')
    add_bone_collection('Arm.L (IK)', ui_row=10)
    add_bone_collection('Arm.L (FK)', ui_row=11, ui_title='FK')
    add_bone_collection('Arm.L (Tweak)', ui_row=12, ui_title='Tweak')
    add_bone_collection('Arm.R (IK)', ui_row=10)
    add_bone_collection('Arm.R (FK)', ui_row=11, ui_title='FK')
    add_bone_collection('Arm.R (Tweak)', ui_row=12, ui_title='Tweak')
    add_bone_collection('Leg.L (IK)', ui_row=14)
    add_bone_collection('Leg.L (FK)', ui_row=15, ui_title='FK')
    add_bone_collection('Leg.L (Tweak)', ui_row=16, ui_title='Tweak')
    add_bone_collection('Leg.R (IK)', ui_row=14)
    add_bone_collection('Leg.R (FK)', ui_row=15, ui_title='FK')
    add_bone_collection('Leg.R (Tweak)', ui_row=16, ui_title='Tweak')

    bones = {}

    bone = arm.edit_bones.new('Hip')
    bone.head = 0.0000, 0.0395, 0.1427
    bone.tail = 0.0000, 0.0153, 0.1837
    bone.roll = 0.0000
    bone.use_connect = False
    bones['Hip'] = bone.name
    bone = arm.edit_bones.new('upper_arm.L')
    bone.head = 0.0636, 0.0000, 0.2740
    bone.tail = 0.1108, 0.0045, 0.2561
    bone.roll = 1.9283
    bone.use_connect = False
    bones['upper_arm.L'] = bone.name
    bone = arm.edit_bones.new('upper_arm.R')
    bone.head = -0.0636, 0.0000, 0.2740
    bone.tail = -0.1108, 0.0045, 0.2561
    bone.roll = -1.9283
    bone.use_connect = False
    bones['upper_arm.R'] = bone.name
    bone = arm.edit_bones.new('thigh.L')
    bone.head = 0.0530, 0.0017, 0.1471
    bone.tail = 0.0530, -0.0039, 0.0737
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Hip']]
    bones['thigh.L'] = bone.name
    bone = arm.edit_bones.new('thigh.R')
    bone.head = -0.0530, 0.0017, 0.1471
    bone.tail = -0.0530, -0.0039, 0.0737
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Hip']]
    bones['thigh.R'] = bone.name
    bone = arm.edit_bones.new('Abdomen')
    bone.head = 0.0000, 0.0153, 0.1837
    bone.tail = 0.0000, 0.0111, 0.2374
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Hip']]
    bones['Abdomen'] = bone.name
    bone = arm.edit_bones.new('forearm.L')
    bone.head = 0.1108, 0.0045, 0.2561
    bone.tail = 0.1545, -0.0080, 0.2365
    bone.roll = 1.9906
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['upper_arm.L']]
    bones['forearm.L'] = bone.name
    bone = arm.edit_bones.new('forearm.R')
    bone.head = -0.1108, 0.0045, 0.2561
    bone.tail = -0.1545, -0.0080, 0.2365
    bone.roll = -1.9906
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['upper_arm.R']]
    bones['forearm.R'] = bone.name
    bone = arm.edit_bones.new('shin.L')
    bone.head = 0.0530, -0.0039, 0.0737
    bone.tail = 0.0530, 0.0022, 0.0117
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thigh.L']]
    bones['shin.L'] = bone.name
    bone = arm.edit_bones.new('shin.R')
    bone.head = -0.0530, -0.0039, 0.0737
    bone.tail = -0.0530, 0.0022, 0.0117
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['thigh.R']]
    bones['shin.R'] = bone.name
    bone = arm.edit_bones.new('Chest')
    bone.head = 0.0000, 0.0111, 0.2374
    bone.tail = 0.0000, 0.0111, 0.2916
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Abdomen']]
    bones['Chest'] = bone.name
    bone = arm.edit_bones.new('forearm.L.001')
    bone.head = 0.1545, -0.0080, 0.2365
    bone.tail = 0.1748, -0.0080, 0.2249
    bone.roll = 2.0653
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['forearm.L']]
    bones['forearm.L.001'] = bone.name
    bone = arm.edit_bones.new('forearm.R.001')
    bone.head = -0.1545, -0.0080, 0.2365
    bone.tail = -0.1748, -0.0080, 0.2249
    bone.roll = -2.0653
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['forearm.R']]
    bones['forearm.R.001'] = bone.name
    bone = arm.edit_bones.new('foot.L')
    bone.head = 0.0530, 0.0022, 0.0117
    bone.tail = 0.0530, -0.0128, 0.0023
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['shin.L']]
    bones['foot.L'] = bone.name
    bone = arm.edit_bones.new('foot.R')
    bone.head = -0.0530, 0.0022, 0.0117
    bone.tail = -0.0530, -0.0128, 0.0023
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['shin.R']]
    bones['foot.R'] = bone.name
    bone = arm.edit_bones.new('Neck')
    bone.head = 0.0000, 0.0125, 0.2949
    bone.tail = 0.0000, 0.0165, 0.3245
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Chest']]
    bones['Neck'] = bone.name
    bone = arm.edit_bones.new('toe.L')
    bone.head = 0.0530, -0.0128, 0.0023
    bone.tail = 0.0530, -0.0220, 0.0023
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['toe.L'] = bone.name
    bone = arm.edit_bones.new('heel.02.L')
    bone.head = 0.0478, 0.0063, 0.0000
    bone.tail = 0.0588, 0.0063, 0.0000
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['foot.L']]
    bones['heel.02.L'] = bone.name
    bone = arm.edit_bones.new('toe.R')
    bone.head = -0.0530, -0.0128, 0.0023
    bone.tail = -0.0530, -0.0220, 0.0023
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['toe.R'] = bone.name
    bone = arm.edit_bones.new('heel.02.R')
    bone.head = -0.0478, 0.0063, 0.0000
    bone.tail = -0.0588, 0.0063, 0.0000
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['foot.R']]
    bones['heel.02.R'] = bone.name
    bone = arm.edit_bones.new('Head')
    bone.head = 0.0000, 0.0165, 0.3245
    bone.tail = 0.0000, 0.0149, 0.4097
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Neck']]
    bones['Head'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['Hip']]
    pbone.rigify_type = 'game_ready.spine_unity_humanoid'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.gr_spine_override_parent = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_spine_parent = 'NONE'
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Torso (Tweak)')
    try:
        pbone.rigify_parameters.gr_spine_torso_widget_offset = Vector((0.0, 0.0, 0.0))
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_spine_torso_widget_rotation = Euler((0.0, 0.0, 0.0), 'XYZ')
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_spine_tweak_widget_offset = Vector((0.0, 0.0, 0.0))
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_spine_fk_widget_offset = Vector((0.0, 0.0, 0.0))
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_spine_torso_widget_scale = Vector((1.7829999923706055, 1.7829999923706055, 1.7829999923706055))
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_spine_hips_widget_scale = Vector((1.0, 1.0, 1.0))
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_spine_hips_widget_rotation = Euler((0.0, 0.0, 0.0), 'XYZ')
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_spine_hips_widget_offset = Vector((0.0, 0.0, 0.0))
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_spine_chest_widget_scale = Vector((1.0, 1.0, 1.0))
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_spine_fk_widget_scale = Vector((1.0, 0.0, 1.0))
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.L']]
    pbone.rigify_type = 'game_ready.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Arm.L (FK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Arm.L (Tweak)')
    try:
        pbone.rigify_parameters.gr_arm_override_parent = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_arm_parent = 'DEF-Chest'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['upper_arm.R']]
    pbone.rigify_type = 'game_ready.arm'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Arm.R (FK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Arm.R (Tweak)')
    try:
        pbone.rigify_parameters.gr_arm_override_parent = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_arm_parent = 'DEF-Chest'
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.L']]
    pbone.rigify_type = 'game_ready.leg_toes'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    try:
        pbone.rigify_parameters.limb_type = 'leg'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_ik_toe = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_toe_roll = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.segments = 3
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_toes_override_parent = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_toes_parent = 'DEF-Hip'
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Leg.L (FK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Leg.L (Tweak)')
    try:
        pbone.rigify_parameters.make_custom_pivot = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['thigh.R']]
    pbone.rigify_type = 'game_ready.leg_toes'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    try:
        pbone.rigify_parameters.limb_type = 'leg'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_ik_toe = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.ik_local_location = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.extra_toe_roll = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.segments = 3
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbones = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_toes_override_parent = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_toes_parent = 'DEF-Hip'
    except AttributeError:
        pass
    assign_bone_collection_refs(pbone.rigify_parameters, 'fk', 'Leg.L (FK)')
    assign_bone_collection_refs(pbone.rigify_parameters, 'tweak', 'Leg.L (Tweak)')
    try:
        pbone.rigify_parameters.make_custom_pivot = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Abdomen']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    pbone = obj.pose.bones[bones['forearm.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    pbone = obj.pose.bones[bones['forearm.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    pbone = obj.pose.bones[bones['shin.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    pbone = obj.pose.bones[bones['shin.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    pbone = obj.pose.bones[bones['Chest']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    pbone = obj.pose.bones[bones['forearm.L.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.L (IK)')
    pbone = obj.pose.bones[bones['forearm.R.001']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Arm.R (IK)')
    pbone = obj.pose.bones[bones['foot.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    pbone = obj.pose.bones[bones['foot.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    pbone = obj.pose.bones[bones['Neck']]
    pbone.rigify_type = 'game_ready.super_copy'
    pbone.lock_location = (True, True, True)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parent_bone = ''
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_sc_def_parent = 'DEF-Chest'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_sc_widget_scale = Vector((4.978000164031982, 1.0, 4.9029998779296875))
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_sc_widget_offset = Vector((0.0, 0.004999999888241291, 0.0))
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['toe.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    pbone = obj.pose.bones[bones['heel.02.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.L (IK)')
    pbone = obj.pose.bones[bones['toe.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    pbone = obj.pose.bones[bones['heel.02.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Leg.R (IK)')
    pbone = obj.pose.bones[bones['Head']]
    pbone.rigify_type = 'game_ready.super_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    assign_bone_collections(pbone, 'Torso')
    try:
        pbone.rigify_parameters.super_copy_widget_type = 'cube'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.parent_bone = ''
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_sc_def_parent = 'DEF-Neck'
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_sc_widget_scale = Vector((1.9019999504089355, 1.5, 1.5))
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.gr_sc_widget_offset = Vector((0.0, 0.050000011920928955, 0.007000000216066837))
    except AttributeError:
        pass

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.collections.active_index = 0

    return bones


if __name__ == "__main__":
    create(bpy.context.active_object)
